### ISSUE TITLE
Some warning errors for `-Wall -Werror`

### ISSUE THREAD

**Issue by waruqi** [uael/sv#1]
I'm trying to integrate libsv to xmake, but there are some warning errors when compiling with cflags `-Wall -Werror`.

```
src/comp.c:95:29: error: '&&' within '||' [-Werror,-Wlogical-op-parentheses]
    if (str[*offset] == '-' && sv_id_read(&self->prerelease, str, len, (++*offset, offset))
```

**Comment by uael** [comment]
Ok I'm going to fix it

**Comment by uael** [comment]
@waruqi 
> error: /usr/include/stdlib.h:131:25: error: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]

I just `add_cflags("-Wno-nullability-completeness")` `add_cxxflags("-Wno-nullability-completeness")` ?

**Comment by uael** [comment]
[travis failed build](https://travis-ci.org/uael/sv/jobs/231462406#L364)

**Comment by waruqi** [comment]
@uael Ok. 👌

**Comment by uael** [comment]
Ok fixed now !

**Comment by waruqi** [comment]
great! 👍
