### ISSUE TITLE
On the role of the semver_id API

### ISSUE THREAD

**Issue by marcomaggi** [uael/sv#22]
What is it meant to be exactly?  It is the mechanism under the semver API, but it also duplicates some features?

**Comment by uael** [comment]
You're right, I think the id api could be private without duplicate

**Comment by marcomaggi** [comment]
After further study of the code, I think I get it better.  A version must start with the triplet of numbers, while with the id reader we parse any sequence of identifiers.

**Comment by uael** [comment]
Yep :smile:
