### ISSUE TITLE
Validating the build metadata

### ISSUE THREAD

**Issue by marcomaggi** [uael/sv#23]
It is my understanding that `+x86_64` is an **invalid** build metadata, because it contains an underscore character.  While `+x86-64` is correct.  There is no validation of metadata in the library?

**Comment by uael** [comment]
I'm not aware about all of this :smile: can you explain it to me ?

**Comment by marcomaggi** [comment]
As described in [Semantic Versioning 2.0.0](http://semver.org/), at point 10 of the specification:

> Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty.

**Comment by uael** [comment]
As you can see the parser actually act like described [id.c:64](https://github.com/uael/sv/blob/master/src/id.c#L64). Where did you find this invalid build ?

**Comment by marcomaggi** [comment]
It is a misunderstanding of mine on the role of the id API.  When using the semver API, the following function:

```C
void
doc_example_versions_2_3 (void)
{
  printf("--- %s:\n", __func__);
  static const char	input_str[] = "1.2.3-alpha.7+x86_64";
  semver_t	version;
  size_t	offset = 0;
  char		rv;

  rv = semver_read(&version, input_str, strlen(input_str), &offset);
  if (0 == rv) {
    printf("major=%d, minor=%d, patch=%d, ",
	   version.major, version.minor, version.patch);
    printf("prerelease=");
    semver_id_fwrite(&version.prerelease, stdout);
    printf(", ");
    printf("build=");
    semver_id_fwrite(&version.build, stdout);
    printf("\n");
  }
  semver_dtor(&version);
}
```

prints:

```
--- doc_example_versions_2_3:
major=1, minor=2, patch=3, prerelease=alpha.7, build=x86
```

only `x86` is considered build metadata.  Is it how it is supposed to be?

**Comment by uael** [comment]
Yes exactly. `_` is not accepted
