### ISSUE TITLE
failed to parse build number with zero prefix

### ISSUE THREAD

**Issue by waruqi** [uael/sv#51]
When I parse the string and numeric build number, it works normally, but if there is a 0 prefix in the build number, the parsing fails

Is this a specification requirement for the semantic version? Or is it a bug?

> ^(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)(?:-(?P<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?P<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$

I saw the specification, build metadata can contain zero prefix.

> 1.0.1+HEAD.1234

It works, build: {HEAD, 1234}

> 1.0.1+HEAD.01234

It does not work, parse `01234` failed

https://github.com/uael/sv/blob/a1af47b0db5baa608025911f518e7e943cf24484/src/id.c#L68-L70

**Comment by waruqi** [comment]
there is an online checker. https://jubianchi.github.io/semver-check/#/1.0.1%2BHEAD.001/1.0.1%2BHEAD.001

The zero prefix constraint may only be valid for prerelease.

**Comment by waruqi** [comment]
I open a pr to try fix it. https://github.com/uael/sv/pull/52

**Comment by uael** [comment]
Thanks mate 👍
