### ISSUE TITLE
Weird initialisation of id

### ISSUE THREAD

**Issue by marcomaggi** [uael/sv#7]
On my `x86_64-slackware-linux-gnu`, both GCC and CLang complain about the initialisation in `id.c`:

```
#ifndef _MSC_VER
  *self = (semver_id_t) {1};
#else
```

which is indeed weird; I do not know what the symbol `_MSC_VER` is.

By the way, why the field `numeric` is a `char`?  Being that the library uses C99, it may be more appropriate to use a `bool`?

**Comment by uael** [comment]
The symbol `_MSC_VER` is defined by the compiler msvc on Windows, otherwise yes a bool can be used but `stdbool.h` come in recent version of the msvc compiler, a simple and cross platform tweak is
```c
#if !defined(__cplusplus) && _MSC_VER && _MSC_VER < 1900
# define bool	unsigned char
# define true	1
# define false	0
# define __bool_true_false_are_defined	1
#else
# ifdef __cplusplus
#  include <cstdbool>
# else
#  include <stdbool.h>
# endif
#endif
```

**Comment by marcomaggi** [comment]
So such initialisation is wrong when compiling on non-Windows platforms?

**Comment by uael** [comment]
It's the opposite, indeed it's not wrong but not officially supported. What's the warning of both clan and gcc ?

**Comment by marcomaggi** [comment]
GCC does this:

```
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I../src -I../include -Wall -Wextra -pedantic -O3 -MT src/id.lo -MD -MP -MF src/.deps/id.Tpo -c ../src/id.c  -fPIC -DPIC -o src/.libs/id.o
../src/id.c: In function 'semver_id_ctor':
../src/id.c:40:3: warning: missing initializer for field 'num' of 'semver_id_t {aka struct semver_id_t}' [-Wmissing-field-initializers]
   *self = (semver_id_t) {1};
   ^
In file included from ../src/id.c:31:0:
../include/semver.h:53:7: note: 'num' declared here
   int num;
       ^
```

and clang does this:

```
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I.. -I../src -I../include -Wall -Wextra -pedantic -O3 -MT src/id.lo -MD -MP -MF src/.deps/id.Tpo -c ../src/id.c  -fPIC -DPIC -o src/.libs/id.o
../src/id.c:40:27: warning: missing field 'num' initializer [-Wmissing-field-initializers]
  *self = (semver_id_t) {1};
                          ^
1 warning generated.
```

clang also complains about other similar initialisations.

IMHO you should just use the field-by-field initialisation on all the platforms.

**Comment by uael** [comment]
The warning is relative to this missing initialized fields, you can disable it by compiling with `-Wno-missing-field-initializers`
It does not affect anything, I maybe should use `calloc` instead of `malloc` to avoid field initialization.

**Comment by marcomaggi** [comment]
I am paranoid, so I try very hard to avoid the `-Wno-` options.  Is it all right if client code recycles an old data structure and some field is not reinitialised?  Also if the internal representation of the data is changed?

**Comment by uael** [comment]
When setting something with `{0}`, the memory is all set to 0 recursively, even missing initialized fields.
Warnings on initializers are a plague. They are responsible for the fact that many people don't use default initializers where they could and should. Shame on gcc and Co that they enable this with -Wall.
